# frozen_string_literal: true

require 'i18n'
require 'yaml'
require_relative 'config/i18n'
require_relative 'lib/application/uploader/uploader'
require_relative 'lib/application/validate/validate'
require_relative 'lib/application/validating_data'
require_relative 'lib/application/check_errors'
require_relative 'lib/application/difficulty'
require_relative 'lib/application/game'
require_relative 'lib/application/console'
require_relative 'lib/application/game_user'
require_relative 'lib/application/game_messages'
require_relative 'lib/application/game_process'
require_relative 'lib/application/version'
